const jsVer = "3.0.236";
module.exports = [
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "长留",
        siteName: "changliu",
        imgDate: "210714",
        jsVersion: jsVer,
        DLName: "download_changliu",
        DLNameOl: "download_changliu_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "zl",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "天骄",
        siteName: "tianjiao",
        imgDate: "210709",
        jsVersion: jsVer,
        DLName: "download_tianjiao",
        DLNameOl: "download_tianjiao_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "tj",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "口碑",
        siteName: "koubei",
        imgDate: "210624",
        jsVersion: jsVer,
        DLName: "download_koubei",
        DLNameOl: "download_koubei_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "kb",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "龙腾",
        siteName: "longteng",
        imgDate: "21622",
        jsVersion: jsVer,
        DLName: "download_longteng",
        DLNameOl: "download_longteng_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "lt",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "当红",
        siteName: "danghong",
        imgDate: "210609",
        jsVersion: jsVer,
        DLName: "download_danghong",
        DLNameOl: "download_danghong_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "dh",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "当红",
        siteName: "danghong2",
        imgDate: "230627",
        jsVersion: jsVer,
        DLName: "download_danghong2",
        DLNameOl: "download_danghong2_ol",
        DLAndroidUrl: "https://dh2.lefanyx.com/4a1ee479112220d2ad65b9a0c7a3b474.apk",
        DLIOSUrl: "https://tren567.com/uW7Ky",
        folderName: "dh2"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "万象",
        siteName: "wanxiang",
        imgDate: "210525",
        jsVersion: jsVer,
        DLName: "download_wanxiang",
        DLNameOl: "download_wanxiang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "wx",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "招财",
        siteName: "zhaocai",
        imgDate: "210513",
        jsVersion: jsVer,
        DLName: "download_zhaocai",
        DLNameOl: "download_zhaocai_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "zc",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "信条",
        siteName: "xin",
        imgDate: "210510",
        jsVersion: jsVer,
        DLName: "download_xin",
        DLNameOl: "download_xin_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "xt",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "鼻祖",
        siteName: "bizu",
        imgDate: "210728",
        jsVersion: jsVer,
        DLName: "download_bizu",
        DLNameOl: "download_bizu_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "bz1",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "超巨",
        siteName: "chaoju",
        imgDate: "210422",
        jsVersion: jsVer,
        DLName: "download_chaoju",
        DLNameOl: "download_chaoju_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "cj",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "灵犀",
        siteName: "lingxi",
        imgDate: "210414",
        jsVersion: jsVer,
        DLName: "download_lingxi",
        DLNameOl: "download_lingxi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "lx",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "泰斗",
        siteName: "taidou",
        imgDate: "231227",
        jsVersion: jsVer,
        DLName: "download_taidou",
        DLNameOl: "download_taidou_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "fd",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "宝藏",
        siteName: "baozang",
        imgDate: "210331",
        jsVersion: jsVer,
        DLName: "download_baozang",
        DLNameOl: "download_baozang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "bz",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "百赢",
        siteName: "baiying",
        imgDate: "210223",
        jsVersion: jsVer,
        DLName: "download_baiying",
        DLNameOl: "download_baiying_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "by",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module2",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "心动",
        siteName: "xindong",
        imgDate: "210322",
        jsVersion: jsVer,
        DLName: "download_xindong",
        DLNameOl: "download_xindong_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "xd",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "高光",
        siteName: "gaoguang",
        imgDate: "210318",
        jsVersion: jsVer,
        DLName: "download_gaoguang",
        DLNameOl: "download_gaoguang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "gg",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module2",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "流金",
        siteName: "liujin",
        imgDate: "210305",
        jsVersion: jsVer,
        DLName: "download_liujin",
        DLNameOl: "download_liujin_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "lj",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "千秋",
        siteName: "qianqiu",
        imgDate: "210302",
        jsVersion: jsVer,
        DLName: "download_qianqiu",
        DLNameOl: "download_qianqiu_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "qq",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "开运",
        siteName: "kaiyun",
        imgDate: "210224",
        jsVersion: jsVer,
        DLName: "download_kaiyun",
        DLNameOl: "download_kaiyun_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ky",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "觉醒",
        siteName: "juexing",
        imgDate: "210222",
        jsVersion: jsVer,
        DLName: "download_juexing",
        DLNameOl: "download_juexing_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "jx",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "首席",
        siteName: "shouxi",
        imgDate: "210208",
        jsVersion: jsVer,
        DLName: "download_shouxi",
        DLNameOl: "download_shouxi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "sx",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "牛运",
        siteName: "niuyun",
        imgDate: "210122",
        jsVersion: jsVer,
        DLName: "download_niuyun",
        DLNameOl: "download_niuyun_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ny",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "顶流",
        siteName: "dinliu",
        imgDate: "210104",
        jsVersion: jsVer,
        DLName: "download_dinliu",
        DLNameOl: "download_dinliu_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "dl",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "天选",
        siteName: "tianxuan",
        imgDate: "201230",
        jsVersion: jsVer,
        DLName: "download_tianxuan",
        DLNameOl: "download_tianxuan_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "tx",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "向往",
        siteName: "xiangwang",
        imgDate: "201228",
        jsVersion: jsVer,
        DLName: "download_xiangwang",
        DLNameOl: "download_xiangwang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "xw",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "春宵",
        siteName: "chunxiao",
        imgDate: "201222",
        jsVersion: jsVer,
        DLName: "download_chunxiao",
        DLNameOl: "download_chunxiao_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "cx",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "真香",
        siteName: "zhenxiang",
        imgDate: "201209",
        jsVersion: jsVer,
        DLName: "download_zx",
        DLNameOl: "download_zx_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "zx",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "唯一",
        siteName: "weiyi",
        imgDate: "201110",
        jsVersion: jsVer,
        DLName: "download_weiyi",
        DLNameOl: "download_weiyi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "wy",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "神话",
        siteName: "shenhua",
        imgDate: "201006",
        jsVersion: jsVer,
        DLName: "download_shenhua",
        DLNameOl: "download_shenhua_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "sh",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "",
        jsModule: "module1",
        title: "龙飞",
        siteName: "longfei",
        imgDate: "230918",
        jsVersion: jsVer,
        DLName: "download_longfei",
        DLNameOl: "download_longfei_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "lf",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "无双",
        siteName: "wushuang",
        imgDate: "231110",
        jsVersion: jsVer,
        DLName: "download_wushuang",
        DLNameOl: "download_wushuang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ws",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module3",
        mengcengHtmlModule: "module3",
        jsModule: "module1",
        title: "荣耀俱乐部",
        siteName: "rongyao",
        imgDate: "210727",
        jsVersion: jsVer,
        DLName: "download_rongyao",
        DLNameOl: "download_rongyao_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ry",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "王道",
        siteName: "wangdao",
        imgDate: "210727",
        jsVersion: jsVer,
        DLName: "download_wangdao",
        DLNameOl: "download_wangdao_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "wd",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "王炸",
        siteName: "wangzha",
        imgDate: "210727",
        jsVersion: jsVer,
        DLName: "download_wangzha",
        DLNameOl: "download_wangzha_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "wd",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "上阳",
        siteName: "shangyang",
        imgDate: "210721",
        jsVersion: jsVer,
        DLName: "download_shangyang",
        DLNameOl: "download_shangyang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "sy",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "同庆",
        siteName: "tongqing",
        imgDate: "210728",
        jsVersion: jsVer,
        DLName: "download_tongqing",
        DLNameOl: "download_tongqing_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "tq",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "半夏",
        siteName: "banxia",
        imgDate: "210802",
        jsVersion: jsVer,
        DLName: "download_banxia",
        DLNameOl: "download_banxia_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "bx",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "奥英",
        siteName: "aoying",
        imgDate: "210811",
        jsVersion: jsVer,
        DLName: "download_aoying",
        DLNameOl: "download_aoying_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ay",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "神州",
        siteName: "shenzhou",
        imgDate: "210819",
        jsVersion: jsVer,
        DLName: "download_shenzhou",
        DLNameOl: "download_shenzhou_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "sz",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "御赐",
        siteName: "yuci",
        imgDate: "210825",
        jsVersion: jsVer,
        DLName: "download_yuci",
        DLNameOl: "download_yuci_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "yc",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "巨量",
        siteName: "juliang",
        imgDate: "210902",
        jsVersion: jsVer,
        DLName: "download_juliang",
        DLNameOl: "download_juliang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "jl",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "千川",
        siteName: "qianchuan",
        imgDate: "210906",
        jsVersion: jsVer,
        DLName: "download_qianchuan",
        DLNameOl: "download_qianchuan_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "qc",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "王权",
        siteName: "wangquan",
        imgDate: "211001",
        jsVersion: jsVer,
        DLName: "download_wangquan",
        DLNameOl: "download_wangquan_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "wq",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "蓝筹",
        siteName: "lanchou",
        imgDate: "210915",
        jsVersion: jsVer,
        DLName: "download_lanchou",
        DLNameOl: "download_lanchou_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "lc",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "金选",
        siteName: "jinxuan",
        imgDate: "210930",
        jsVersion: jsVer,
        DLName: "download_jinxuan",
        DLNameOl: "download_jinxuan_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "jxi",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "头号",
        siteName: "touhao",
        imgDate: "211111",
        jsVersion: jsVer,
        DLName: "download_touhao",
        DLNameOl: "download_touhao_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "th",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "至爱",
        siteName: "zhiai",
        imgDate: "211115",
        jsVersion: jsVer,
        DLName: "download_zhiai",
        DLNameOl: "download_zhiai_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "za",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "先知",
        siteName: "xianzhi",
        imgDate: "211125",
        jsVersion: jsVer,
        DLName: "download_xianzhi",
        DLNameOl: "download_xianzhi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "xz",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "庆丰",
        siteName: "qingfeng",
        imgDate: "211215",
        jsVersion: jsVer,
        DLName: "download_qingfeng",
        DLNameOl: "download_qingfeng_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "qf",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "千寻",
        siteName: "qianxun",
        imgDate: "220114",
        jsVersion: jsVer,
        DLName: "download_qianxun",
        DLNameOl: "download_qianxun_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "qx",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "虎啸",
        siteName: "huxiao",
        imgDate: "220121",
        jsVersion: jsVer,
        DLName: "download_huxiao",
        DLNameOl: "download_huxiao_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "hx",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "盖世",
        siteName: "gaishi",
        imgDate: "220225",
        jsVersion: jsVer,
        DLName: "download_gaishi",
        DLNameOl: "download_gaishi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "gs",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "嘉行",
        siteName: "jiahang",
        imgDate: "220325",
        jsVersion: jsVer,
        DLName: "download_jiahang",
        DLNameOl: "download_jiahang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "jia",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "浪潮",
        siteName: "langchao",
        imgDate: "220401",
        jsVersion: jsVer,
        DLName: "download_langchao",
        DLNameOl: "download_langchao_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "la",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "霸榜",
        siteName: "babang",
        imgDate: "220420",
        jsVersion: jsVer,
        DLName: "download_babang",
        DLNameOl: "download_babang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "bb",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "伊人",
        siteName: "yiren",
        imgDate: "220422",
        jsVersion: jsVer,
        DLName: "download_yiren",
        DLNameOl: "download_yiren_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "yr",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "华彩",
        siteName: "huacai",
        imgDate: "220513",
        jsVersion: jsVer,
        DLName: "download_huacai",
        DLNameOl: "download_huacai_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "hc",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "正阳",
        siteName: "zheng",
        imgDate: "220527",
        jsVersion: jsVer,
        DLName: "download_zheng",
        DLNameOl: "download_zheng_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "zy6",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "泰隆",
        siteName: "tailong",
        imgDate: "220715",
        jsVersion: jsVer,
        DLName: "download_tailong",
        DLNameOl: "download_tailong_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "tl",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "心水",
        siteName: "xinshui",
        imgDate: "220715",
        jsVersion: jsVer,
        DLName: "download_xinshui",
        DLNameOl: "download_xinshui_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "xs",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "钟意",
        siteName: "zhongyi",
        imgDate: "220729",
        jsVersion: jsVer,
        DLName: "download_zhongyi",
        DLNameOl: "download_zhongyi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/123123",
        folderName: "zy",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "全优",
        siteName: "quanyou",
        imgDate: "230627",
        jsVersion: jsVer,
        DLName: "download_quanyou",
        DLNameOl: "download_quanyou_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "qy",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "斗南",
        siteName: "dounan",
        imgDate: "220908",
        jsVersion: jsVer,
        DLName: "download_dounan",
        DLNameOl: "download_dounan_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "dn",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "丰利",
        siteName: "fengli",
        imgDate: "220908",
        jsVersion: jsVer,
        DLName: "download_fengli",
        DLNameOl: "download_fengli_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "fl",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "富佳",
        siteName: "fujia",
        imgDate: "221019",
        jsVersion: jsVer,
        DLName: "download_fujia",
        DLNameOl: "download_fujia_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "fj",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "领队",
        siteName: "lingdui",
        imgDate: "230105",
        jsVersion: jsVer,
        DLName: "download_lingdui",
        DLNameOl: "download_lingdui_ol",
        DLAndroidUrl: "https://ld.pmsjx.com/4d83ec00330b9ea133934ed0c69e5ee6.apk",
        DLIOSUrl: "https://tren567.com/JoFrI",
        folderName: "ld"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "荣盛",
        siteName: "rongsheng",
        imgDate: "231221",
        jsVersion: jsVer,
        DLName: "download_rongsheng",
        DLNameOl: "download_rongsheng_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "rs",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "如意",
        siteName: "ruyi",
        imgDate: "231221",
        jsVersion: jsVer,
        DLName: "download_ruyi",
        DLNameOl: "download_ruyi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ry1",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "创世",
        siteName: "chuangshi",
        imgDate: "230119",
        jsVersion: jsVer,
        DLName: "download_chuangshi",
        DLNameOl: "download_chuangshi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "cs",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "华丰",
        siteName: "huafeng",
        imgDate: "231221",
        jsVersion: jsVer,
        DLName: "download_huafeng",
        DLNameOl: "download_huafeng_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "hf",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "旷古",
        siteName: "kuanggu",
        imgDate: "231221",
        jsVersion: jsVer,
        DLName: "download_kuanggu",
        DLNameOl: "download_kuanggu_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "kg",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "拔新",
        siteName: "baxin",
        imgDate: "230406",
        jsVersion: jsVer,
        DLName: "download_baxin",
        DLNameOl: "download_baxin_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "bx1",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "福连",
        siteName: "fulian",
        imgDate: "231221",
        jsVersion: jsVer,
        DLName: "download_fulian",
        DLNameOl: "download_fulian_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "fl2",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "浩宇",
        siteName: "haoyu",
        imgDate: "231221",
        jsVersion: jsVer,
        DLName: "download_haoyu",
        DLNameOl: "download_haoyu_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "hy",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "匠心",
        siteName: "jiangxin",
        imgDate: "231221",
        jsVersion: jsVer,
        DLName: "download_jiangxin",
        DLNameOl: "download_jiangxin_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "jx2",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "云顶",
        siteName: "yunding",
        imgDate: "231221",
        jsVersion: jsVer,
        DLName: "download_yunding",
        DLNameOl: "download_yunding_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "yd",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "华耀",
        siteName: "huayao",
        imgDate: "230526",
        jsVersion: jsVer,
        DLName: "download_huayao",
        DLNameOl: "download_huayao_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "hy1",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "龙舟",
        siteName: "longzhou",
        imgDate: "230602",
        jsVersion: jsVer,
        DLName: "download_longzhou",
        DLNameOl: "download_longzhou_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/a2efe48dffde0046388d5e5cbaea3db6.apk",
        DLIOSUrl: "https://yclpsj.com/tC2Qx",
        folderName: "lz"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "龙舟A",
        siteName: "longzhouA",
        imgDate: "230609",
        jsVersion: jsVer,
        DLName: "download_longzhouA",
        DLNameOl: "download_longzhouA_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "lz11",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "龙舟B",
        siteName: "longzhouB",
        imgDate: "230609",
        jsVersion: jsVer,
        DLName: "download_longzhouB",
        DLNameOl: "download_longzhouB_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "lz3",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "瑞赢A",
        siteName: "ruiyingA",
        imgDate: "230609",
        jsVersion: jsVer,
        DLName: "download_ruiyingA",
        DLNameOl: "download_ruiyingA_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ry2",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "瑞赢B",
        siteName: "ruiyingB",
        imgDate: "231221",
        jsVersion: jsVer,
        DLName: "download_longzhouB",
        DLNameOl: "download_longzhouB_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ry3",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "狂飙",
        siteName: "kuangbiao",
        imgDate: "230628",
        jsVersion: jsVer,
        DLName: "download_kuangbiao",
        DLNameOl: "download_kuangbiao_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "kb1",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "紫霄",
        siteName: "zixiao",
        imgDate: "230630",
        jsVersion: jsVer,
        DLName: "download_zixiao",
        DLNameOl: "download_zixiao_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "zx1",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "大同",
        siteName: "datong",
        imgDate: "230630",
        jsVersion: jsVer,
        DLName: "download_datong",
        DLNameOl: "download_datong_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "dt",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "天一",
        siteName: "tianyi",
        imgDate: "230719",
        jsVersion: jsVer,
        DLName: "download_tianyi",
        DLNameOl: "download_tianyi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ty",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "英皇",
        siteName: "yinghuang",
        imgDate: "230712",
        jsVersion: jsVer,
        DLName: "download_yinghuang",
        DLNameOl: "download_yinghuang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "yh",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "如是",
        siteName: "rushi",
        imgDate: "230712",
        jsVersion: jsVer,
        DLName: "download_rushi",
        DLNameOl: "download_rushi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "rs1",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "欧皇",
        siteName: "ouhuang",
        imgDate: "230712",
        jsVersion: jsVer,
        DLName: "download_ouhuang",
        DLNameOl: "download_ouhuang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "oh",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "质点",
        siteName: "zhidian",
        imgDate: "230724",
        jsVersion: jsVer,
        DLName: "download_zhidian",
        DLNameOl: "download_zhidian_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "zd",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "华庆",
        siteName: "huaqing",
        imgDate: "230804",
        jsVersion: jsVer,
        DLName: "download_huaqing",
        DLNameOl: "download_huaqing_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "hq",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "秋意",
        siteName: "qiuyi",
        imgDate: "230810",
        jsVersion: jsVer,
        DLName: "download_qiuyi",
        DLNameOl: "download_qiuyi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "qy1",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "来乐",
        siteName: "laile",
        imgDate: "231225",
        jsVersion: jsVer,
        DLName: "download_laile",
        DLNameOl: "download_laile_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ll",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "得胜",
        siteName: "desheng",
        imgDate: "231106",
        jsVersion: jsVer,
        DLName: "download_desheng",
        DLNameOl: "download_desheng_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "ds",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "欢瑞",
        siteName: "huanrui",
        imgDate: "231225",
        jsVersion: jsVer,
        DLName: "download_huanrui",
        DLNameOl: "download_huanrui_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "hr",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "跃进",
        siteName: "yuejin",
        imgDate: "230901",
        jsVersion: jsVer,
        DLName: "download_yuejin",
        DLNameOl: "download_yuejin_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "yj",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "海泽",
        siteName: "haize",
        imgDate: "230906",
        jsVersion: jsVer,
        DLName: "download_haize",
        DLNameOl: "download_haize_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "hz",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "永来",
        siteName: "yonglai",
        imgDate: "230915",
        jsVersion: jsVer,
        DLName: "download_yonglai",
        DLNameOl: "download_yonglai_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "yl",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "纪年",
        siteName: "jinian",
        imgDate: "231221",
        jsVersion: jsVer,
        DLName: "download_jinian",
        DLNameOl: "download_jinian_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/e0b9eadfc63cce5bd6aff913bd92c344.apk",
        DLIOSUrl: "https://tren567.com/6wO1",
        folderName: "jn"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "月宫",
        siteName: "yuegong",
        imgDate: "231106",
        jsVersion: jsVer,
        DLName: "download_yuegong",
        DLNameOl: "download_yuegong_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "yg",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "完美",
        siteName: "wanmei",
        imgDate: "231106",
        jsVersion: jsVer,
        DLName: "download_wanmei",
        DLNameOl: "download_wanmei_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "wm",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "尽欢",
        siteName: "jinhuan",
        imgDate: "231107",
        jsVersion: jsVer,
        DLName: "download_jinhuan",
        DLNameOl: "download_jinhuan_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/11c27782e1339b6b3727b3e324ab117e.apk",
        DLIOSUrl: "https://tren567.com/1D4U",
        folderName: "jh"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "永恒",
        siteName: "yongheng",
        imgDate: "231107",
        jsVersion: jsVer,
        DLName: "download_yongheng",
        DLNameOl: "download_yongheng_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "yh1",
        group: "lowActive"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "光彩",
        siteName: "guangcai",
        imgDate: "240102",
        jsVersion: jsVer,
        DLName: "download_guangcai",
        DLNameOl: "download_guangcai_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/dd3bcafc5fbeacbd5778b305a854b9f9.apk",
        DLIOSUrl: "https://tren567.com/mog5",
        folderName: "gc"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "峥光",
        siteName: "zhengguang",
        imgDate: "231107",
        jsVersion: jsVer,
        DLName: "download_zhengguang",
        DLNameOl: "download_zhengguang_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/d2ff3eb865efa12a0480c7a7fbc23af7.apk",
        DLIOSUrl: "https://tren567.com/WQeB",
        folderName: "zg"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "庆幸",
        siteName: "qingxing",
        imgDate: "231101",
        jsVersion: jsVer,
        DLName: "download_qingxing",
        DLNameOl: "download_qingxing_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b1e8d59a74ed325b7944b81173b0f145.apk",
        DLIOSUrl: "https://tren567.com/PAf4",
        folderName: "qx1"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "邀月",
        siteName: "yaoyue",
        imgDate: "240104",
        jsVersion: jsVer,
        DLName: "download_yaoyue",
        DLNameOl: "download_yaoyue_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/edf9d8079bbf30a224f70c117b409092.apk",
        DLIOSUrl: "https://tren567.com/89xi",
        folderName: "yy"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "泰来",
        siteName: "tailai",
        imgDate: "231116",
        jsVersion: jsVer,
        DLName: "download_tailai",
        DLNameOl: "download_tailai_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/75f4cb300e983724df80810c0db00c88.apk",
        DLIOSUrl: "https://tren567.com/YWbR",
        folderName: "tl1"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "先锋",
        siteName: "xianfeng",
        imgDate: "231122",
        jsVersion: jsVer,
        DLName: "download_xianfeng",
        DLNameOl: "download_xianfeng_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/e5079bb14db9932697fe95d0d770f9af.apk",
        DLIOSUrl: "https://tren567.com/Gj9N",
        folderName: "xf"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "王者",
        siteName: "wangzhe",
        imgDate: "231130",
        jsVersion: jsVer,
        DLName: "download_wangzhe",
        DLNameOl: "download_wangzhe_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/b7077a662ed929597a141864010701ec.apk",
        DLIOSUrl: "https://tren567.com/XCeF",
        folderName: "wz"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "环星",
        siteName: "huanxing",
        imgDate: "231206",
        jsVersion: jsVer,
        DLName: "download_huanxing",
        DLNameOl: "download_huanxing_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/8a847d10211bb411cb659e9592fb78c5.apk",
        DLIOSUrl: "https://tren567.com/qT8d",
        folderName: "hx1"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "即兴",
        siteName: "jixing",
        imgDate: "231225",
        jsVersion: jsVer,
        DLName: "download_jixing",
        DLNameOl: "download_jixing_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/7246cf6dd74063e4ed958b6e6e6cbc03.apk",
        DLIOSUrl: "https://tren567.com/sxtP",
        folderName: "jx3"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "飞夫",
        siteName: "feifu",
        imgDate: "231220",
        jsVersion: jsVer,
        DLName: "download_feifu",
        DLNameOl: "download_feifu_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/5fbf96c243cd5e3fb134b11d99a53543.apk",
        DLIOSUrl: "https://tren567.com/0Xlo",
        folderName: "ff"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "凌志",
        siteName: "lingzhi",
        imgDate: "240103",
        jsVersion: jsVer,
        DLName: "download_lingzhi",
        DLNameOl: "download_lingzhi_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/dd74f335621354437837d96b352fb4e7.apk",
        DLIOSUrl: "https://tren567.com/nrWU",
        folderName: "lz1"
    },
    {
        guanwangHtmlModule: "module1",
        mengcengHtmlModule: "module1",
        jsModule: "module1",
        title: "葡乐",
        siteName: "pule",
        imgDate: "240104",
        jsVersion: jsVer,
        DLName: "download_pule",
        DLNameOl: "download_pule_ol",
        DLAndroidUrl: "https://mubao-channel.chappystar.com/78d66c753d0b8c24228f2a5dcc70af81.apk",
        DLIOSUrl: "https://tren567.com/8BKi",
        folderName: "pl"
    }
];
